# Generated by Django 4.1.3 on 2022-11-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_user_email_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='People',
        ),
    ]
