# Generated by Django 4.1.3 on 2022-12-07 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0006_alter_instancebooks_id_user_alter_lecturer_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancebooks',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
