# Generated by Django 4.1.3 on 2022-12-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_alter_instancebooks_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancebooks',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
