# Generated by Django 4.1.3 on 2022-12-08 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0009_remove_instancebooks_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateField()),
                ('max_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('id_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.books')),
                ('id_library', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lib.library')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InstanceBooks',
        ),
    ]
