# Generated by Django 4.1.3 on 2022-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_instancebook_delete_instancebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancebook',
            name='borrowing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancebook',
            name='max_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
