# Generated by Django 4.1.3 on 2022-12-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0012_lecturegroup_alter_lecturer_id_lg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureGroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.lecturegroup')),
            ],
        ),
    ]
