# Generated by Django 4.1.3 on 2022-12-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0017_alter_lecturegroup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturegroup',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
