# Generated by Django 4.1.3 on 2023-01-19 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0018_alter_lecturegroup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instancebook',
            name='id_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.library'),
        ),
        migrations.AlterField(
            model_name='lecturegroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
